### ISSUE TITLE
A private draft

### ISSUE THREAD

**Issue by shnarazk** [shnarazk/helix#2]
Feature proposal: paste-string

I'd like to add a way to insert fixed strings as a kind of simple snippet.                    
(It seems that there was no discussion about snippet so far.)                                      
Here's my use case.                                                                                
                                                                                                  
```toml                                                                                           
[keys.insert."\\"]                                                                                
"m" = ":paste-string macro_rules! {($_: expr) => { match {} };}"                                  
"w" = ":paste-string 𝕨"  # for BQN, an APL dialect.                                               
"T" = ":paste-string ⍋"                                                                           
"l" = ":paste-string ⟜"                                                                           
```                                                                                               
                                                                                                  
A simple implementation by this PR required just adding one `TypableCommand` and underlying function. So if there's no undergoing development...

**Comment by shnarazk** [comment]
```toml

[keys.insert."\\"]
"`" = ":paste-string ˜"
"~" = ":paste-string ¬"
"1" = ":paste-string ˜"
"!" = ":paste-string ⎉"
"3" = ":paste-string ⁼"
"4" = ":paste-string ⌜"
"5" = ":paste-string ´"
"6" = ":paste-string ˝"
"8" = ":paste-string ∞"
"9" = ":paste-string ¯"
"(" = ":paste-string ⟨"
"0" = ":paste-string •"
")" = ":paste-string ⟩"
minus = ":paste-string ÷"
"_" = ":paste-string √"
plus = ":paste-string ×"
"|" = ":paste-string ⋆"
"w" = ":paste-string 𝕨"
"T" = ":paste-string ⍋"
"{" = ":paste-string ⊣"
"}" = ":paste-string ⊢"
"h" = ":paste-string ⊸"
"j" = ":paste-string ∘"
"l" = ":paste-string ⟜"
"x" = ":paste-string 𝕩"
"c" = ":paste-string ↓"
"V" = ":paste-string ⍒"
"b" = ":paste-string ⌊"
"B" = ":paste-string ⌈"
"m" = ":paste-string ≡"
"M" = ":paste-string ≢"
"." = ":paste-string ≍"
space = ":paste-string ‿"
```
